x-environment: &environment
  DB_PATH: /app/db/db.sqlite3
  RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672

x-db-volumes: &db-volumes
  - ./docker_data/db/:/app/db/

x-build-args: &build_args
  POETRY_HOME: /opt/poetry
  POETRY_CACHE_DIR: /tmp/poetry_cache/text_processing

x-build: &build
  context: .
  args:
    <<: *build_args

x-env_file: &env_file
  path: .env.shared
  required: false

x-depends: &depends
  rabbitmq:
    condition: service_healthy

x-user: &user ${UID:-1000}:${UID:-1000}

services:
  init-volumes-permissions:
    image: alpine:3.20.3
    environment:
      CUSTOM_UID: ${UID:-1000}
      CUSTOM_GID: ${UID:-1000}
    entrypoint:
      - sh
      - -c
      - |
        [ ! -d /data/rabbitmq/data ] && mkdir -p /data/rabbitmq/data;
        [ ! -d /data/rabbitmq/log ] && mkdir -p /data/rabbitmq/log;
        [ ! -d /data/db ] && mkdir /data/db;
        chown -R $$CUSTOM_UID:$$CUSTOM_GID /data
    volumes:
      - ./docker_data/:/data/
  rabbitmq:
    user: *user
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - ./docker_data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker_data/rabbitmq/log/:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 15s
      start_interval: 1s
    depends_on:
      - init-volumes-permissions
  web_api:
    user: *user
    build:
      <<: *build
      args:
        <<: *build_args
        SERVICE_NAME: web_api
    ports:
      - 127.0.0.1:8000:8000
    depends_on: *depends
    volumes: *db-volumes
    env_file:
      - *env_file
      - path: .env.web_api
        required: false
    environment:
      <<: *environment
      WEB_API_HOST: 0.0.0.0
  task_processor:
    user: *user
    build:
      <<: *build
      args:
        <<: *build_args
        SERVICE_NAME: task_processor
    depends_on: *depends
    volumes: *db-volumes
    env_file:
      - *env_file
      - path: .env.task_processor
        required: false
    environment: *environment
